/*
 * AddProjectsDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package main.ui;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;

import javax.swing.JFileChooser;

import main.util.ProjectProperties;

/**
 *
 * @author  __USER__
 */
public class AddProjectsDialog extends javax.swing.JDialog {

	/** Creates new form AddProjectsDialog */
	DeployToolFrame parentFrame ;
	ProjectProperties dto;
	
	public AddProjectsDialog(java.awt.Frame parent, boolean modal,ProjectProperties dto) {
		super(parent, modal);
		parentFrame=(DeployToolFrame) parent;
		this.setLocation(parent.getX()+20, parent.getY()+20);
		this.dto=dto;
		initComponents();
	}
	
	public AddProjectsDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		parentFrame=(DeployToolFrame) parent;
		this.setLocation(parent.getX()+20, parent.getY()+20);
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	File path = null;

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		okBtn = new javax.swing.JButton();
		cancelBtn = new javax.swing.JButton();

		setDefaultCloseOperation(DISPOSE_ON_CLOSE);
		
		jLabel1.setText("Project Name");

		jLabel2.setText("Path");
		
		if(dto != null){
			if(dto.getKey() != null && dto.getKey().length()>0){
				jTextField1.setText(dto.getKey());
			}
			
			if(dto.getValue() != null && dto.getValue().length()>0){
				jTextField2.setText(dto.getValue());
			}
		}

		jButton1.setText("Browse");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel3.setText("Add New Project");

		okBtn.setText("Ok");
		okBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okBtnActionPerformed(evt);
			}
		});

		cancelBtn.setText("Cancel");
		cancelBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(34, 34, 34)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jLabel3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														213,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						84,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						67,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jTextField2,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														262,
																														Short.MAX_VALUE)
																												.addComponent(
																														jTextField1,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														258,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										jButton1)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createSequentialGroup()
																								.addComponent(
																										okBtn)
																								.addGap(50,
																										50,
																										50)
																								.addComponent(
																										cancelBtn)
																								.addGap(126,
																										126,
																										126)))))
								.addContainerGap(29,
										javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										22,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jLabel1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														28,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jLabel2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		jTextField2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(
																		jButton1)))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										26, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(cancelBtn)
												.addComponent(okBtn))
								.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
		this.setVisible(false);
	}

	private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {
		Properties prop = new Properties();
		boolean val = validateAddProjectsDialog();
		if(!val){
			try {
				prop.load(new FileInputStream(parentFrame.getDeployToolHome()+"\\config.properties"));
				FileOutputStream fos = new FileOutputStream(parentFrame.getDeployToolHome()+"\\config.properties");
				if(dto != null && dto.getAction() != null && dto.getAction().equalsIgnoreCase("edit")){
					prop.remove(dto.getKey());
				}
				prop.setProperty(jTextField1.getText(), jTextField2.getText());
				prop.save(fos, null);
				fos.close();
			} catch (FileNotFoundException e) {
				e.printStackTrace();
			} catch (IOException e) {
				e.printStackTrace();
			}
			this.setVisible(false);
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		final JFileChooser fileChooser = new JFileChooser();
		fileChooser.setDialogTitle("Choose Directory");
		fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		fileChooser.setAcceptAllFileFilterUsed(false);
		int result = fileChooser.showOpenDialog(this);

		if (result == JFileChooser.APPROVE_OPTION) {
			path = fileChooser.getSelectedFile();
			jTextField2.setText(path.getAbsolutePath());
		}

	}
	
	private boolean validateAddProjectsDialog(){
		
		if(jTextField1 !=null && (jTextField1.getText() == null || jTextField1.getText().length() == 0)){
			InfoDialog dialog = new InfoDialog(parentFrame, "Error","Please Enter a Project name");
			dialog.setSize(300,100);
			dialog.setVisible(true);
			return true;
		}
		if(jTextField2 !=null && (jTextField2.getText() == null || jTextField2.getText().length() == 0)){
			InfoDialog dialog = new InfoDialog(parentFrame, "Error","Please choose a directory");
			dialog.setSize(300,100);
			dialog.setVisible(true);
			return true;
		}
		return false;
	}
	
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				AddProjectsDialog dialog = new AddProjectsDialog(new javax.swing.JFrame(),
						true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton cancelBtn;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JButton okBtn;
	// End of variables declaration//GEN-END:variables
}